FROM python:3.10-slim 
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements_mlflow.txt .
RUN pip install --no-cache-dir -r requirements_mlflow.txt

EXPOSE 5000

ENV MLFLOW_S3_ENDPOINT_URL=
ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=
ENV AWS_SESSION_TOKEN=
ENV AWS_DEFAULT_REGION=

ENV MLFLOW_ARTIFACT_ROOT=
ENV MLFLOW_BACKEND_STORE_URI=

RUN printenv

ENTRYPOINT mlflow server -h 0.0.0.0 -p 5000 --default-artifact-root s3://mlflow-tc/ --backend-store-uri postgresql://mlflow:Wi10203040@database-1.c1wyileysnho.us-east-1.rds.amazonaws.com:5432/mlflow_tests
# ENTRYPOINT mlflow server -h 0.0.0.0 -p 5000 --default-artifact-root $MLFLOW_ARTIFACT_ROOT --backend-store-uri $MLFLOW_BACKEND_STORE_URI


# docker build -D --no-cache -f Dockerfile-mlflow -t mlflow-tc . 
# docker run -d -p 5000:5000
# remove all containers: docker container prune
